name: focus-loop

services:
  server:
    container_name: focus-loop-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3073:3000"
    environment:
      - MONGO_URI=mongodb://${MONGODB_INITDB_ROOT_USERNAME}:${MONGODB_INITDB_ROOT_PASSWORD}@mongo/
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
    profiles:
      - backend
    command: ["npm", "run", "dev"]

  client-web:
    container_name: focus-loop-client-web
    build:
      context: ./client-web
      dockerfile: Dockerfile
    ports:
      - "3037:3000"
    profiles:
      - frontend

  mongo:
    container_name: focus-loop-mongo
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "bash", "-c", "echo 'db.adminCommand(\"ping\")' | mongo localhost:27017 --quiet"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mongodb_data:
